const KEY="midinero.v2";
let movements=JSON.parse(localStorage.getItem(KEY)||"[]");
let type="expense", step=1;
const $=id=>document.getElementById(id);
const cats={income:["Trabajo","Web","Venta","Paga","Otros ingresos"],expense:["Comida","Transporte","Ocio","Ropa","Tecnología","Casa","Estudios","Otros"]};
const money=n=>new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR"}).format(Number(n)||0);
const save=()=>localStorage.setItem(KEY,JSON.stringify(movements));
function setType(t){type=t;document.querySelectorAll(".typecard").forEach(b=>b.classList.toggle("active",b.dataset.type===t));$("formTitle").textContent=t==="income"?"Nuevo ingreso":"Nuevo gasto";$('category').innerHTML=cats[t].map(x=>`<option>${x}</option>`).join("");}
function nowLocal(){let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
function openForm(t){setType(t);step=1;$('amount').value="";$('concept').value="";$('method').value="Tarjeta";$('date').value=nowLocal();$('amountError').textContent="";$('sheet').classList.remove('hidden');$('sheet').setAttribute('aria-hidden','false');updateStep();}
function closeForm(){$('sheet').classList.add('hidden');$('sheet').setAttribute('aria-hidden','true')}
function updateStep(){document.querySelectorAll('.step').forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===step));$('stepLabel').textContent=`Paso ${step} de 4`;$('progressBar').style.width=`${step*25}%`;$('backStep').style.visibility=step===1?'hidden':'visible';$('nextStep').classList.toggle('hidden',step===4);$('form').querySelector('.save').classList.toggle('hidden',step!==4);if(step===4)renderSummary();if(step===2)setTimeout(()=>$('amount').focus(),50);}
function validateStep(){if(step===1)return true;if(step===2){let n=Number($('amount').value);if(!Number.isFinite(n)||n<=0){$('amountError').textContent="Introduce una cantidad mayor que 0.";return false}$('amountError').textContent="";return true}if(step===3){if(!$('concept').value.trim()){ $('concept').focus();return false}return true}return true}
function next(){if(!validateStep())return;if(step<4){step++;updateStep()}}
function prev(){if(step>1){step--;updateStep()}else closeForm()}
function renderSummary(){$('summary').innerHTML=`<div class="summary-row"><span>Tipo</span><b>${type==='income'?'Ingreso':'Gasto'}</b></div><div class="summary-row"><span>Importe</span><b>${money(Number($('amount').value))}</b></div><div class="summary-row"><span>Concepto</span><b>${esc($('concept').value.trim())}</b></div><div class="summary-row"><span>Categoría</span><b>${esc($('category').value)}</b></div><div class="summary-row"><span>Método</span><b>${esc($('method').value)}</b></div>`}
function render(){let totalI=movements.filter(m=>m.type==='income').reduce((s,m)=>s+m.amount,0),totalE=movements.filter(m=>m.type==='expense').reduce((s,m)=>s+m.amount,0);$('balance').textContent=money(totalI-totalE);$('income').textContent=money(totalI);$('expense').textContent=money(totalE);let now=new Date(),mi=movements.filter(m=>{let d=new Date(m.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}),i=mi.filter(m=>m.type==='income').reduce((s,m)=>s+m.amount,0),e=mi.filter(m=>m.type==='expense').reduce((s,m)=>s+m.amount,0);$('monthBalance').textContent=money(i-e);let max=Math.max(i+e,1);$('incomeBar').style.width=i/max*100+'%';$('expenseBar').style.width=e/max*100+'%';let q=$('search').value.toLowerCase().trim(),f=$('filter').value;let list=movements.filter(m=>(f==='all'||m.type===f)&&((m.concept+' '+m.category+' '+m.method).toLowerCase().includes(q))).sort((a,b)=>new Date(b.date)-new Date(a.date));$('list').innerHTML=list.length?list.map(m=>{let d=new Date(m.date);return `<div class="movement"><div class="dot ${m.type==='income'?'in':'out'}">${m.type==='income'?'↓':'↑'}</div><div class="mtext"><b>${esc(m.concept)}</b><small>${esc(m.category)} · ${esc(m.method)} · ${d.toLocaleDateString('es-ES')}</small></div><div class="amount ${m.type==='income'?'in':'out'}">${m.type==='income'?'+':'−'}${money(m.amount)}</div><button class="delete" type="button" data-delete="${m.id}" aria-label="Eliminar movimiento">×</button></div>`}).join(''):'<div class="empty">No hay movimientos.</div>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function removeMove(id){if(confirm('¿Eliminar este movimiento?')){movements=movements.filter(m=>m.id!==id);save();render()}}
function exportCSV(){let csv='Fecha,Tipo,Importe,Concepto,Categoria,Metodo\n'+movements.map(m=>[new Date(m.date).toISOString(),m.type,m.amount.toFixed(2).replace('.',','),m.concept,m.category,m.method].map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');let blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='MiDinero.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('addIncome').onclick=()=>openForm('income');$('addExpense').onclick=()=>openForm('expense');$('x').onclick=closeForm;$('closeSheet').onclick=closeForm;$('backStep').onclick=prev;$('nextStep').onclick=next;document.querySelectorAll('.typecard').forEach(b=>b.onclick=()=>setType(b.dataset.type));$('form').onsubmit=e=>{e.preventDefault();if(step!==4||!validateStep())return;let amount=Number($('amount').value);movements.push({id:crypto.randomUUID(),type,amount,concept:$('concept').value.trim(),category:$('category').value,method:$('method').value,date:$('date').value});save();closeForm();render()};$('list').addEventListener('click',e=>{let b=e.target.closest('[data-delete]');if(b)removeMove(b.dataset.delete)});$('search').oninput=render;$('filter').onchange=render;$('themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('midinero.theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('midinero.theme')==='light')document.body.classList.add('light');if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});setType('expense');render();
