const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const cats={income:['Trabajo','Web','Venta','Paga','Otros ingresos'],expense:['Comida','Transporte','Ocio','Ropa','Tecnología','Casa','Estudios','Otros']};
const LOCAL_KEY='midinero.v2'; const THEME_KEY='midinero.theme';
let movements=JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]'); let type='expense', step=1, authMode='login', session=null, cryptoKey=null, supabase=null;
const cfg=window.MIDINERO_CONFIG||{};
if(window.supabase&&cfg.supabaseUrl&&cfg.supabaseAnonKey&&!cfg.supabaseUrl.includes('TU-PROYECTO')) supabase=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
const saveLocal=()=>localStorage.setItem(LOCAL_KEY,JSON.stringify(movements));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function nowLocal(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
function setType(t){type=t;$('category').innerHTML=cats[t].map(x=>`<option>${x}</option>`).join('');}
function showStep(n){step=n;document.querySelectorAll('.step').forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===n));$('progressBar').style.width=(n/4*100)+'%';$('stepLabel').textContent=`Paso ${n} de 4`;$('backBtn').classList.toggle('hidden',n===1);$('nextBtn').classList.toggle('hidden',n===4);$('saveBtn').classList.toggle('hidden',n!==4); if(n===4) updateReview(); const focus={2:'amount',3:'concept'}[n]; if(focus) setTimeout(()=>$(focus).focus(),100)}
function openForm(t){setType(t);$('amount').value='';$('concept').value='';$('method').value='Tarjeta';$('date').value=nowLocal();$('formTitle').textContent=t==='income'?'Nuevo ingreso':'Nuevo gasto';$('sheet').classList.remove('hidden');showStep(1)}
function validStep(){if(step===1&&!type)return false;if(step===2){const a=Number($('amount').value);if(!a||a<=0){alert('Introduce una cantidad válida.');return false}}if(step===3&&!$('concept').value.trim()){alert('Escribe un concepto.');return false}return true}
function updateReview(){$('review').innerHTML=`<div><span>Tipo</span><b>${type==='income'?'💰 Ingreso':'💸 Gasto'}</b></div><div><span>Importe</span><b>${money($('amount').value)}</b></div><div><span>Concepto</span><b>${esc($('concept').value.trim())}</b></div><div><span>Categoría</span><b>${esc($('category').value)}</b></div>`}
function render(){const totalI=movements.filter(m=>m.type==='income').reduce((s,m)=>s+m.amount,0),totalE=movements.filter(m=>m.type==='expense').reduce((s,m)=>s+m.amount,0);$('balance').textContent=money(totalI-totalE);$('income').textContent=money(totalI);$('expense').textContent=money(totalE);const now=new Date(),mi=movements.filter(m=>{const d=new Date(m.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}),i=mi.filter(m=>m.type==='income').reduce((s,m)=>s+m.amount,0),e=mi.filter(m=>m.type==='expense').reduce((s,m)=>s+m.amount,0);$('monthBalance').textContent=money(i-e);const max=Math.max(i+e,1);$('incomeBar').style.width=i/max*100+'%';$('expenseBar').style.width=e/max*100+'%';const q=$('search').value.toLowerCase(),f=$('filter').value;const list=movements.filter(m=>(f==='all'||m.type===f)&&(`${m.concept} ${m.category} ${m.method}`).toLowerCase().includes(q)).sort((a,b)=>new Date(b.date)-new Date(a.date));$('list').innerHTML=list.length?list.map(m=>{const d=new Date(m.date);return `<div class="movement"><div class="dot ${m.type==='income'?'in':'out'}">${m.type==='income'?'↓':'↑'}</div><div class="mtext"><b>${esc(m.concept)}</b><small>${esc(m.category)} · ${esc(m.method)} · ${d.toLocaleDateString('es-ES')}</small></div><div class="amount ${m.type==='income'?'in':'out'}">${m.type==='income'?'+':'−'}${money(m.amount)}</div><button class="delete" data-id="${esc(m.id)}">×</button></div>`}).join(''):'<div class="empty">No hay movimientos.</div>';document.querySelectorAll('.delete').forEach(b=>b.onclick=()=>removeMove(b.dataset.id))}
async function removeMove(id){movements=movements.filter(m=>m.id!==id);saveLocal();render();if(session&&supabase)await supabase.from('movements').delete().eq('id',id)}
function exportCSV(){const csv='Fecha,Tipo,Importe,Concepto,Categoria,Metodo\n'+movements.map(m=>[new Date(m.date).toISOString(),m.type,m.amount.toFixed(2).replace('.',','),m.concept,m.category,m.method].map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');download('MiDinero.csv','\ufeff'+csv,'text/csv;charset=utf-8')}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function deriveKey(password,saltB64){const enc=new TextEncoder(),base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:b64ToBytes(saltB64),iterations:250000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
function b64(bytes){let s='';bytes.forEach(x=>s+=String.fromCharCode(x));return btoa(s)} function b64ToBytes(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function encrypt(obj){const iv=crypto.getRandomValues(new Uint8Array(12));const data=new TextEncoder().encode(JSON.stringify(obj));const ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},cryptoKey,data));return b64(iv)+'.'+b64(ct)}
async function decrypt(payload){const [iv,ct]=payload.split('.');const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(iv)},cryptoKey,b64ToBytes(ct));return JSON.parse(new TextDecoder().decode(plain))}
async function ensureProfile(user,password){let {data:p}=await supabase.from('profiles').select('salt').eq('id',user.id).maybeSingle();if(!p){const salt=crypto.getRandomValues(new Uint8Array(16));const saltB64=b64(salt);const r=await supabase.from('profiles').insert({id:user.id,salt:saltB64});if(r.error)throw r.error;p={salt:saltB64}}cryptoKey=await deriveKey(password,p.salt)}
async function cloudPull(){if(!session||!supabase||!cryptoKey)return;const {data,error}=await supabase.from('movements').select('*').order('created_at',{ascending:false});if(error)throw error;const decoded=[];for(const row of data||[]){try{decoded.push(await decrypt(row.payload))}catch(e){throw new Error('No se pudo descifrar uno de tus movimientos. Usa tu contraseña de la cuenta.')}}movements=decoded;saveLocal();render()}
async function cloudPush(){if(!session||!supabase||!cryptoKey)return;const {data:rows}=await supabase.from('movements').select('id');const ids=new Set((rows||[]).map(r=>r.id));for(const m of movements){if(!ids.has(m.id)){const payload=await encrypt(m);const r=await supabase.from('movements').insert({id:m.id,user_id:session.user.id,type:m.type,amount:m.amount,payload});if(r.error)throw r.error}}}
async function sync(){if(!session||!supabase)return;await cloudPull();await cloudPush();await cloudPull()}
async function authSubmit(e){e.preventDefault();if(!supabase){showAuthError('Primero configura Supabase en config.js.');return}const email=$('authEmail').value.trim(),password=$('authPassword').value;if(password.length<8){showAuthError('La contraseña debe tener al menos 8 caracteres.');return}$('authSubmit').disabled=true;try{let result;if(authMode==='signup')result=await supabase.auth.signUp({email,password});else result=await supabase.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(authMode==='signup'&&!result.data.session){showAuthError('Cuenta creada. Revisa tu email para confirmar la cuenta y luego inicia sesión.');return}session=result.data.session;await ensureProfile(session.user,password);if(movements.length)await cloudPush();await cloudPull();$('authSheet').classList.add('hidden');updateAccount()}catch(err){showAuthError(err.message||'No se pudo iniciar sesión.')}finally{$('authSubmit').disabled=false}}
function showAuthError(msg){$('authError').textContent=msg;$('authError').classList.remove('hidden')}
function openAuth(mode='login'){authMode=mode;$('authTitle').textContent=mode==='signup'?'Crear cuenta':'Iniciar sesión';$('authHint').textContent=mode==='signup'?'Tu cuenta sincronizará tus datos entre dispositivos.':'Tus datos están cifrados antes de enviarse a la nube.';$('authSubmit').textContent=mode==='signup'?'Crear cuenta':'Entrar';$('authSwitch').textContent=mode==='signup'?'Ya tengo una cuenta':'Crear una cuenta';$('authError').classList.add('hidden');$('authForm').reset();$('authSheet').classList.remove('hidden')}
function updateAccount(){if(session){$('accountEmail').textContent=session.user.email;$('accountBtn').textContent=(session.user.email||'?')[0].toUpperCase()}else $('accountBtn').textContent='?'}
async function boot(){document.body.classList.toggle('light',localStorage.getItem(THEME_KEY)==='light');if(supabase){const r=await supabase.auth.getSession();session=r.data.session;if(session)updateAccount();supabase.auth.onAuthStateChange((_e,s)=>{session=s;updateAccount()})}render()}
$('addIncome').onclick=()=>openForm('income');$('addExpense').onclick=()=>openForm('expense');$('x').onclick=()=>$('sheet').classList.add('hidden');$('closeSheet').onclick=()=>$('sheet').classList.add('hidden');document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{setType(b.dataset.type);showStep(2)});$('nextBtn').onclick=()=>{if(validStep())showStep(step+1)};$('backBtn').onclick=()=>showStep(step-1);$('form').onsubmit=async e=>{e.preventDefault();if(!validStep())return;const m={id:crypto.randomUUID(),type,amount:Number($('amount').value),concept:$('concept').value.trim(),category:$('category').value,method:$('method').value,date:$('date').value};movements.push(m);saveLocal();render();$('sheet').classList.add('hidden');if(session&&supabase){try{await cloudPush()}catch(err){alert('Guardado en el móvil. La sincronización falló: '+err.message)}}};$('search').oninput=render;$('filter').onchange=render;$('exportBtn').onclick=exportCSV;$('themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem(THEME_KEY,document.body.classList.contains('light')?'light':'dark')};$('accountBtn').onclick=()=>session?$('accountSheet').classList.remove('hidden'):openAuth();$('closeAuth').onclick=()=>$('authSheet').classList.add('hidden');$('authX').onclick=()=>$('authSheet').classList.add('hidden');$('authSwitch').onclick=()=>openAuth(authMode==='login'?'signup':'login');$('authForm').onsubmit=authSubmit;$('closeAccount').onclick=()=>$('accountSheet').classList.add('hidden');$('accountX').onclick=()=>$('accountSheet').classList.add('hidden');$('logoutBtn').onclick=async()=>{if(supabase)await supabase.auth.signOut();session=null;cryptoKey=null;$('accountSheet').classList.add('hidden');updateAccount()};$('syncBtn').onclick=async()=>{try{await sync();alert('☁️ Sincronizado')}catch(e){alert('No se pudo sincronizar: '+e.message)}};$('backupBtn').onclick=exportCSV;
setType('expense');boot();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
