const KEY="midinero.v1";let movements=JSON.parse(localStorage.getItem(KEY)||"[]");let type="expense";
const $=id=>document.getElementById(id);
const cats={income:["Trabajo","Web","Venta","Paga","Otros ingresos"],expense:["Comida","Transporte","Ocio","Ropa","Tecnología","Casa","Estudios","Otros"]};
const money=n=>new Intl.NumberFormat("es-ES",{style:"currency",currency:"EUR"}).format(n);
const save=()=>localStorage.setItem(KEY,JSON.stringify(movements));
function setType(t){type=t;document.querySelectorAll(".seg button").forEach(b=>b.classList.toggle("active",b.dataset.type===t));$("formTitle").textContent=t==="income"?"Nuevo ingreso":"Nuevo gasto";$("category").innerHTML=cats[t].map(x=>`<option>${x}</option>`).join("")}
function nowLocal(){let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
function openForm(t){setType(t);$("amount").value="";$("concept").value="";$("method").value="Tarjeta";$("date").value=nowLocal();$("sheet").classList.remove("hidden");$("amount").focus()}
function render(){let totalI=movements.filter(m=>m.type==="income").reduce((s,m)=>s+m.amount,0),totalE=movements.filter(m=>m.type==="expense").reduce((s,m)=>s+m.amount,0);$("balance").textContent=money(totalI-totalE);$("income").textContent=money(totalI);$("expense").textContent=money(totalE);
let now=new Date(),month=now.getMonth(),year=now.getFullYear();let mi=movements.filter(m=>{let d=new Date(m.date);return d.getMonth()===month&&d.getFullYear()===year});let i=mi.filter(m=>m.type==="income").reduce((s,m)=>s+m.amount,0),e=mi.filter(m=>m.type==="expense").reduce((s,m)=>s+m.amount,0);$("monthBalance").textContent=money(i-e);let max=Math.max(i+e,1);$("incomeBar").style.width=(i/max*100)+"%";$("expenseBar").style.width=(e/max*100)+"%";
let q=$("search").value.toLowerCase(),f=$("filter").value;let list=movements.filter(m=>(f==="all"||m.type===f)&&((m.concept+" "+m.category+" "+m.method).toLowerCase().includes(q))).sort((a,b)=>new Date(b.date)-new Date(a.date));$("list").innerHTML=list.length?list.map(m=>{let d=new Date(m.date);return `<div class="movement"><div class="dot ${m.type==="income"?"in":"out"}">${m.type==="income"?"↓":"↑"}</div><div class="mtext"><b>${esc(m.concept)}</b><small>${esc(m.category)} · ${esc(m.method)} · ${d.toLocaleDateString("es-ES")}</small></div><div class="amount ${m.type==="income"?"in":"out"}">${m.type==="income"?"+":"−"}${money(m.amount)}</div><button class="delete" onclick="removeMove('${m.id}')">×</button></div>`}).join(""):'<div class="empty">No hay movimientos.</div>'}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function removeMove(id){movements=movements.filter(m=>m.id!==id);save();render()}
function exportCSV(){let csv="Fecha,Tipo,Importe,Concepto,Categoria,Metodo\n"+movements.map(m=>[new Date(m.date).toISOString(),m.type,m.amount.toFixed(2).replace(".",","),m.concept,m.category,m.method].map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");let blob=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="MiDinero.csv";a.click();URL.revokeObjectURL(a.href)}
$("addIncome").onclick=()=>openForm("income");$("addExpense").onclick=()=>openForm("expense");$("x").onclick=()=>$("sheet").classList.add("hidden");$("closeSheet").onclick=()=>$("sheet").classList.add("hidden");document.querySelectorAll(".seg button").forEach(b=>b.onclick=()=>setType(b.dataset.type));$("search").oninput=render;$("filter").onchange=render;$("exportBtn").onclick=exportCSV;
$("form").onsubmit=e=>{e.preventDefault();let amount=Number($("amount").value);if(!amount||amount<=0)return;movements.push({id:crypto.randomUUID(),type,amount,concept:$("concept").value.trim(),category:$("category").value,method:$("method").value,date:$("date").value});save();$("sheet").classList.add("hidden");render()};
$("themeBtn").onclick=()=>{document.body.classList.toggle("light");localStorage.setItem("midinero.theme",document.body.classList.contains("light")?"light":"dark")};if(localStorage.getItem("midinero.theme")==="light")document.body.classList.add("light");
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});setType("expense");render();
